name: ebroker
description: Welcome to eBroker.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  cupertino_icons: ^1.0.2

  #Firebase
  firebase_dynamic_links: ^5.4.18
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_messaging: ^14.7.20
  firebase_analytics: ^10.1.6
#  firebase_core_platform_interface: 5.0.0

  #Signin
  sign_in_with_apple: ^6.0.0
  google_sign_in: ^6.2.1

  #visuals
  panorama: ^0.4.1
  video_player: ^2.4.10
  youtube_player_flutter: ^9.0.0


  flick_video_player:
    git:
      url: https://github.com/wrteam-anish/flick-video-player.git
      ref: master

  #Network
  http: ^1.0.0
  dio: ^5.4.1

 #Pickers
  country_picker: ^2.0.19
  sms_autofill: ^2.2.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1

  #Animations
  shimmer: ^3.0.0
  rive: ^0.13.1
  lottie: ^3.0.0

#Network
  connectivity_plus: ^6.0.1
  url_launcher: ^6.1.6
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.1
  intl: ^0.18.0

 #image rendering
#  octo_image: ^2.0.0
  flutter_svg: 1.1.6
  cached_network_image: ^3.3.0
  flutter_native_image: 0.0.6+1
  dotted_border: ^2.0.0+3
  flutter_html: ^3.0.0-beta.1
  share_plus: ^8.0.2
  launch_review: ^3.0.1
  #payment gateways
  razorpay_flutter: ^1.3.5
  in_app_purchase: ^3.1.13
  flutter_stripe: ^10.1.1
  flutter_sim_country_code: ^0.1.2
  google_maps_flutter: ^2.6.0
  awesome_notifications: ^0.9.3+1
  device_preview: ^1.1.0
  path_provider: ^2.0.13
  record: ^5.0.4
  audioplayers: ^6.0.0
  image_cropper: ^5.0.1
  permission_handler: ^11.1.0
  open_filex: ^4.3.2
  package_info_plus: ^4.0.2
  fluttertoast: ^8.2.1
  hydrated_bloc: ^9.1.5
  label_marker: ^1.0.1
  flutter_typeahead: ^5.2.0
  geocoding: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  latlong2: ^0.9.0
  encrypt: ^5.0.3
  google_mobile_ads: ^5.0.0
  uni_links: ^0.5.1
  change_app_package_name: ^1.1.0
  youtube_explode_dart: ^2.0.3
  device_info_plus: ^10.0.1


  flutter_paystack:
    git:
      url: https://github.com/wrteam-anish/flutter_paystack.git # Repo link from your profile
      ref: master
  json_view: ^0.4.2
  geolocator: ^11.0.0



dependency_overrides:
#  flutter_svg : ^1.0.0
  intl: ^0.18.0
  js:

  flutter_launcher_icons: ^0.13.1
  image_cropper_for_web:
  motion_sensors:
    git:
      url: https://github.com/zesage/motion_sensors
      ref: master


  # file_version_info: any


dev_dependencies:
  rename: ^3.0.2


  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - assets/image/
   - assets/svg/
   - assets/AppIcon/
   - assets/languages/
   - assets/lottie/
   - assets/riveAnimations/
   - assets/chat_background/
   - assets/chat_background/
   - assets/svg/MultiColorSvg/
   - assets/svg/Logo/
   - assets/svg/Fallback/
   - assets/city.jpg
   - assets/map.png

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800


      
