// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIkYKOn4Qg9u-AS3lblhcBVaMrvUE4920',
    appId: '1:1012152431846:web:c68760265f9a3c91adb727',
    messagingSenderId: '1012152431846',
    projectId: 'vegy-ba5ec',
    authDomain: 'vegy-ba5ec.firebaseapp.com',
    storageBucket: 'vegy-ba5ec.appspot.com',
    measurementId: 'G-BYS5PEMFFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRg2ngj8C2TdJIYjSvHolNtg1V2IAK9W4',
    appId: '1:1012152431846:android:12270191f865ad93adb727',
    messagingSenderId: '1012152431846',
    projectId: 'vegy-ba5ec',
    storageBucket: 'vegy-ba5ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCP24nIzJ3dxQ2HKOSVmRtwJgIUzdNqwM',
    appId: '1:1012152431846:ios:ba9e9ad11bb2370aadb727',
    messagingSenderId: '1012152431846',
    projectId: 'vegy-ba5ec',
    storageBucket: 'vegy-ba5ec.appspot.com',
    iosBundleId: 'com.ebroker.wrteam',
  );
}
